### ISSUE TITLE
BigDecimal

### ISSUE THREAD

**Issue by dgodd** [chanzuckerberg/sorbet-coerce#44]
I had a situation where I wanted to coerce into a BigDecimal/Numeric (I was actually using a T::Struct). The reason for a igDecimal was that the API sometimes receives strings, and sometimes integers (JSON). I want to convert both to a numeric without data loss.

```
TypeCoerce[T.nilable(Integer)].new.from('123') => 123
TypeCoerce[T.nilable(Integer)].new.from(123) => 123

TypeCoerce[T.nilable(Float)].new.from('123.2') => 123.2
TypeCoerce[T.nilable(Float)].new.from(123.2) => 123.2

TypeCoerce[T.nilable(Float)].new.from('2823111111111111111111111111111111111111111111111111111111111111111111111111111111111111.12').round ==> 2823111111111111211310091539389163649541789162060078943821790215899541495486114917515264
```

Given I am using these values for pricing information I can not loose precision (although would be happy with some form of Numeric class with arbitrary precision.

Currently I am parsing the input as a string and then converting to a BigDecimal before usage, however I would rather convert to a BigDecimal during the conversion to a T::Struct.

**Comment by donaldong** [comment]
Hi! I think BigDecimal is supported:
```ruby
TypeCoerce[T.nilable(BigDecimal)].new.from('2823111111111111111111111111111111111111111111111111111111111111111111111111111111111111.12')
=> 0.282311111111111111111111111111111111111111111111111111111111111111111111111111111111111112e88
```

**Comment by diego-silva** [comment]
This is only a problem on Ruby 2.7+ since `BigDecimal.new` was deprecated on Ruby 2.6.

I've created a small PR (#50) with a test case for this and a fix, but I'm happy to discuss other alternatives there. 🙂
