### ISSUE TITLE
Supporting Enum

### ISSUE THREAD

**Issue by hlascelles** [chanzuckerberg/sorbet-coerce#45]
Before I roll my sleeves up and try a PR is there a reason Enums are not supported, or is there something tricky about them I won't expect? 

I can't remove the bug label. Can we get a new issue template that isn't bug or vulnerability?

**Comment by donaldong** [comment]
Hi! I don't expect anything tricky about supporting Enums. It wasn't added because we didn't have any use cases to coerce Enums 😃 your contribution is definitely welcome here!!

> I can't remove the bug label. Can we get a new issue template that isn't bug or vulnerability?

That's good to know! I will look into this.

**Comment by hlascelles** [comment]
Done! https://github.com/chanzuckerberg/sorbet-coerce/pull/46
