### ISSUE TITLE
[Question] about sorbet dependency

### ISSUE THREAD

**Issue by drselump14** [chanzuckerberg/sorbet-coerce#48]
I love this gem. Very useful.

I'm wondering whether it's better to move sorbet dependency to development only? 

The static analysis is only useful  in development mode. In production, the sorbet-runtime is the must have gem IMO.

I'm not sure how sorbet-coerce works, but IMO in runtime the sorbet-coerce  would only need the sorbet-runtime dependency

**Comment by donaldong** [comment]
Hi, you're right! Will move sorbet to dev-dependency. Thanks for catching this!

**Comment by drselump14** [comment]
Great, thanks for the response~
