### ISSUE TITLE
[Question] Accept PR for config flag on how to deal with empty strings

### ISSUE THREAD

**Issue by leifg** [chanzuckerberg/sorbet-coerce#58]
I would love a feature where an empty string is coerced into a nil value.

So something like this:

```ruby
TypeCoerce[T.nilable(String)].new.from('', coerce_empty_to_nil: true)
=> nil
```

This can be super useful when parsing request parameter (empty fields are passed in as an empty string)

Would you accept a PR like this?

**Comment by mattxwang** [comment]
Hi @leifg, after talking to @katyho (my manager + one of the core maintainers) it sounds like a PR would be welcome! Let me know if you are still interested in creating one!

**Comment by leifg** [comment]
Yes, still interested. Let me see what I can come up with on the weekend.
